"""empty message

Revision ID: 146be2ba1e52
Revises: d5a5f84dcac4
Create Date: 2017-09-05 21:33:16.381746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146be2ba1e52'
down_revision = 'd5a5f84dcac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(length=16), nullable=True),
    sa.Column('email', sa.Unicode(length=128), nullable=True),
    sa.Column('expire', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_uid'), 'password_reset_tokens', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_uid'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
