"""empty message

Revision ID: d5a5f84dcac4
Revises: 098eb68fb520
Create Date: 2017-09-02 23:04:09.144440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a5f84dcac4'
down_revision = '098eb68fb520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('name', sa.Unicode(length=32), nullable=True))
    op.add_column('users', sa.Column('register_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'register_time')
    op.drop_column('users', 'name')
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
